### ISSUE TITLE
Activating assert (the size of the buffer should always be a multiple of the atom size)

### ISSUE THREAD

**Issue by ant0nT** [jgbit/vuda#18]
Hi, there! I've tried to run vuda usage example but I've gotten SIGABRT in ./inc/state/logicaldevice.inl file (row #667). hardware: Intel UHD Graphics 630 and Radeon Pro 560X
software: macOS Mojave, Vulkan SDK 1.2.141 with moltenVK
count_noncoherentatomsize = 2048
dst_ptr->m_size = 2000
without assert it executes successfully.

**Comment by jgbit** [comment]
Hello, thanks for trying out VUDA.
I have revisited the documentation for VkMappedMemoryRange -- the asserts for InvalidateMappedMemoryRanges and FlushMappedMemoryRanges should now be correct. Let me know.
Thank you.

**Comment by ant0nT** [comment]
Hello again! I've updated VUDA and now usage example is working fine. Thank you very much!
