### ISSUE TITLE
Q: Passing textures / samplers as parameters

### ISSUE THREAD

**Issue by ib00** [jgbit/vuda#26]
Is it possible to pass in a texture to launchKernel or are only buffer pointers supported?

**Comment by jgbit** [comment]
While in principle possible, VUDA only support calls to cudaMalloc, which in the context of VUDA allocates memory that is bound using vkBindBufferMemory. The access to texture buffers in CUDA is usually handled with calls to cudaCreateTextureObject. VUDA does not currently have an implementation using vkBindImageMemory.

**Comment by ib00** [comment]
Thanks for explanation.
