### ISSUE TITLE
cuda for?

### ISSUE THREAD

**Issue by adfghhfd** [jgbit/vuda#5]
Hello you loop for work in GPU? or CPU?

**Comment by jgbit** [comment]
Hello there, could you please try to restate your question.
VUDA will call a spir-v kernel provided that the right specialization is specified in kernelLaunch().

**Comment by adfghhfd** [comment]
well in the ordinary compiler Visual c ++ if to write the program that it will use cpu, also the cycles for will be processed on cpu too
and I would like to learn from you cycles are processed on GPU?

**Comment by zink-chimaera** [comment]
In general, yes. However, Vulkan is not limited to be executed on the GPU so vuda should have the same constraints. (@jgbit, please correct me if I'm wrong)

**Comment by adfghhfd** [comment]
bro)cycles(code) for in vuda (vulkan)  work? or in cpu)

**Comment by incker** [comment]
Looks like you need a blog. For news
