### ISSUE TITLE
Can't run on Radeon 7370M with opensource driver

### ISSUE THREAD

**Issue by bodqhrohro** [jgbit/vuda#6]
```
bq:19:26:26:/media/d/temp/git/vuda/samples/bandwidthtest$ DRI_PRIME=1 ./bandwidthtest
vk::SystemError: vk::createInstanceUnique: ErrorIncompatibleDriver
```
Installed `mesa-vulkan-drivers`, now I have
```
bq:19:59:23:/media/d/temp/git/vuda/samples/bandwidthtest$ DRI_PRIME=1 ./bandwidthtest
vk::SystemError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed
```

**Comment by jgbit** [comment]
Thank you for checking out vuda. As far as I understand, AMD only provide Vulkan support for their M series from HD 7730M and up. The error message you receive should therefore be expected behavior as the application can not find any Vulkan compatible devices. Check etc. whether you can run on a different setup.

**Comment by bodqhrohro** [comment]
Isn't MESA meant to provide software emulation too, so it should work regardless of whether the graphical card supports Vulkan or not?

**Comment by jgbit** [comment]
I am not too familiar with mesa, but it could be a conflicting driver issue or related since it seems like the system can not find any Vulkan capable devices. Can you try to run vulkaninfo (included in the VulkanSDK) and have a look at the output?

**Comment by bodqhrohro** [comment]
```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.92

/build/vulkan-tools-1.1.92.0~rc3/vulkaninfo/vulkaninfo.c:3448: failed with VK_ERROR_INITIALIZATION_FAILED
```
Okay, I should probably raise the issue to LunarG, as it is unlikely directly related to Vuda, thanks.
